<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <PlatformTarget>x64</PlatformTarget>
    <Platforms>AnyCPU;x64</Platforms>
    <BaseOutputPath>$(SolutionDir)build\</BaseOutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AssemblyName>PulsarModelVisualizar</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="img\**" />
    <EmbeddedResource Remove="img\**" />
    <None Remove="img\**" />
    <Page Remove="img\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="icon.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="icon.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OpenTK" Version="4.9.4" />
    <PackageReference Include="OpenTK.GLWpfControl" Version="4.3.3" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <!--配布用の設定-->
  <!-- 発行時に CalcLib.dll を実行フォルダ一式にコピーする -->
  <Target Name="CopyNativeDlls" AfterTargets="Publish">
    <ItemGroup>
      <NativeDlls Include="$(MSBuildProjectDirectory)\..\build\$(Platform)\$(Configuration)\CalcLib.dll" />
    </ItemGroup>
    <Copy SourceFiles="@(NativeDlls)" DestinationFolder="$(PublishDir)" SkipUnchangedFiles="true" />
  </Target>
  <!-- 発行時に zip ファイルを生成 -->
  <Target Name="CreateZipPackage" AfterTargets="Publish">
    <Delete Files="$(MSBuildProjectDirectory)\..\..\PulsarModelVisualizar.zip" />
    <!--<Exec Command='tar -a -c -f "$(MSBuildProjectDirectory)\..\..\PulsarModelVisualizar.zip" -C "$(PublishDir.TrimEnd(\))" .' />-->
    <Exec Command='powershell -Command "Compress-Archive -Path &quot;$(PublishDir)*&quot; -DestinationPath &quot;$(MSBuildProjectDirectory)\..\..\PulsarModelVisualizar.zip&quot; -Force"' />
  </Target>

</Project>
