<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <PlatformTarget>x64</PlatformTarget>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenTK" Version="4.9.4" />
    <PackageReference Include="OpenTK.GLWpfControl" Version="4.3.3" />
  </ItemGroup>

  <Target Name="CopyNativeDlls" AfterTargets="Build">
    <Copy SourceFiles="$(SolutionDir)\$(Platform)\$(Configuration)\CalcLib.dll" DestinationFolder="$(OutDir)" SkipUnchangedFiles="true" />
  </Target>

</Project>
